### ISSUE TITLE
S.T.J Support + NRT coverage

### ISSUE THREAD

**Issue by Hawxy** [auth0/auth0-aspnetcore-mvc#42]
Thanks for the new package, this works great!

I was wondering if you'd accept PRs for a few ecosystem enhancements:

- Remove Newtonsoft and replace it with System.Text.Json, as its shipped as part of the targets this library supports.
- Provide nullable reference types coverage, as again its supported by the targets and is enabled in project templates by default with .NET 6
- Remove the limited C# 7.1 lang version (I think this was a copy/paste from Auth0.NET?)

 Cheers 👋

**Comment by frederikprijck** [comment]
Hello,

Thanks for reaching out. We definetly appreciate PRs for enhancements. This SDK is (not yet) in Beta, so any feedback is **highly** **appreciated**.

Let me know if you are willing to provide a PR.

Thanks

**Comment by Hawxy** [comment]
Sure, I'll get started on some PRs.

I do have a question about the code style, the C# style here is a bit old school (ie use of `this` and no underscores for private properties). Is this an internal Auth0 convention for C# code and should contributors be following it strictly?

**Comment by frederikprijck** [comment]
@Hawxy That is a fair point. I will do a sweep through the code base to rectify this.

I prefer:

- Not using this
- Using underscore for privates.

I think those guidelines make a good base for the project in general and are in line with https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions, so I will make these changes on the existing code.

Let's ensure any future code that gets added through the mentioned PRs at least follows that.
